config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#welcome', as: :unauthenticated_root
    end
  end

  resources :categories, only: [:index, :show, :new, :destroy, :create,]
  resources :expenses, only: [:index, :show, :new, :destroy, :create,]

end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # relationships
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_and_belongs_to_many :expenses, dependent: :destroy

  # validations
  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
  validates_length_of :name, maximum: 200
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories, dependent: :destroy

  validates :name, presence: true
  validates_length_of :name, maximum: 200
  validates :amount, presence: true, numericality: { greater_than: 0, less_than: 100_000_000 }
  validates :user_id, presence: true
  validates :date_of_expense, presence: true
  validates :categories, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # relationships
  has_many :categories, dependent: :destroy
  has_many :expenses, dependent: :destroy

  # validations
  validates :name, presence: true
  validates_length_of :name, maximum: 200
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success, :messages, :notice, :alert
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :password, :password_confirmation, :email, :image)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :password, :password_confirmation, :email, :current_password, :image)
    end
  end

  protected :update_allowed_parameters
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = setup_categories

    @total_amount = @categories.map(&:total_amount).compact.sum

    @this_month = 0

    @categories.each do |category|
      next unless category.expenses.length.positive?

      @this_month += category.expenses
        .where('date_of_expense >= ?', Date.today.beginning_of_month)
        .where('date_of_expense <= ?', Date.today.end_of_month)
        .sum(:amount)
    end

    @highest_category = @categories.select(&:name).max_by(&:total_amount)
  end

  def new
    @category = Category.new
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to authenticated_root_path
  end

  def show
    data = Category.with_attached_image.find_by_sql("SELECT categories.*,
        COALESCE(SUM(expenses.amount), 0) as total_amount
          from categories
          LEFT JOIN categories_expenses ON categories.id = categories_expenses.category_id
          LEFT JOIN expenses on categories_expenses.expense_id = expenses.id
          WHERE categories.user_id = #{current_user.id}
          AND categories.id = #{params[:id]} GROUP BY categories.id ORDER BY categories.name ASC")
    @category = data[0]
    @expenses = @category.expenses.order(created_at: :desc)
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      redirect_to authenticated_root_path
    else
      render :new
    end
  end

  def category_params
    params.require(:category).permit(:name, :image)
  end

  def setup_categories
    Category.with_attached_image.find_by_sql("SELECT categories.*,
          COALESCE(SUM(expenses.amount), 0) as total_amount
            from categories
            LEFT JOIN categories_expenses ON categories.id = categories_expenses.category_id
            LEFT JOIN expenses on categories_expenses.expense_id = expenses.id
            WHERE categories.user_id = #{current_user.id} GROUP BY categories.id ORDER BY categories.name ASC")
  end

  private :category_params, :setup_categories
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def new
    @expense = Expense.new
    @categories = Category.where(user_id: current_user.id).order(:name)
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.categories << Category.find(params[:expense][:categories].to_i)
    @categories = Category.all
    @expense.user_id = current_user.id
    if @expense.save
      # success('New expense was successfully created.', redirect: true)
      redirect_to category_path(params[:expense][:categories].to_i)
    else
      # failure('Expense was not created because: ', @expense)
      render :new
    end
  end

  def destroy
    expense_to_delete = Expense.find(params[:id])
    expense_to_delete.destroy
    redirect_back(fallback_location: authenticated_root_path)
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :date_of_expense, categories: [])
  end

  private :expense_params
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    # render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/index.html.erb
<div class="card bg-light mb-3 d-flex justify-content-center" style="max-width:95% ; margin:auto" >
    <div class="card-header">EXPENSE SUMMARY</div>
    <div class="card-body container ">
        <div class="row d-flex justify-content-center mt-2">
            <div class="col-4">
              <i class="fa fa-credit-card fa-3x home_icons" aria-hidden="true"></i> 
            </div>
            <div class="col-6">
                <span>
                     <span style="font-size: 0.8rem">This Month </span><br/>
                    <b><%= number_to_currency(@this_month) %></b>
                </span>
            </div>
        </div>
        <div class="row d-flex justify-content-center mt-3">
            <div class="col-4">
                <i class="fa fa-line-chart fa-3x home_icons" aria-hidden="true"></i> 
            </div>
            <div class="col-6">
                <span>
                    <span style="font-size: 0.8rem">Total Expenses </span><br/>
                    <b><%= number_to_currency(@total_amount) %></b></span>
                </span>
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-3">
            <div class="col-4">
                 <i class="fa fa-exclamation fa-3x home_icons" aria-hidden="true"></i> 
            </div>
            <div class="col-6">
       <span style="font-size: 0.8rem">You spend so much on</span> <br/>           
            <% if !@highest_category.nil? && @highest_category.total_amount > 0 %>  
                <b><%= @highest_category.name if @highest_category.name %></b></span>
            <% else %>
                <b>no record yet</b></span>
            <% end %>
    </div>
  </div>
</div>
</div>

<div class="card bg-light mb-3 d-flex justify-content-center" style="max-width:95% ; margin:auto" >
    <div class="card-header">Spending Categories</div>
    <div class="card-body container ">
    
       <% @categories.each do |category| %>



<div class="alert alert-secondary" role="alert">
         




<div class="row d-flex justify-content-center mt-2">
            <div class="col-2">
               <i class="fa fa-tag fa-2x home_icons" aria-hidden="true"></i> 
            </div>
            <div class="col-8  justify-content-center">
                <p class="fs-6"><%= category.name %></p>
                <div style="font-weight: bolder;"><%= number_to_currency(category.total_amount) if category.total_amount.present? %></div>
                <div style="font-weight: bolder;"><%= number_to_currency(0) if !category.total_amount.present? %></div>

            </div>
            <div class="col-2">
               <i class="fa fa-ellipsis-v" aria-hidden="true" data-bs-toggle="dropdown" id="menu-#{category.id}"></i>
                        <ul class="dropdown-menu" aria-labelledby="menu-#{category.id}">
                            <li>
                                <button class="dropdown-item" type="button">
                                     <a href="<%= category_path(category.id) %>">
                                        View
                                    </a>
                                </button>
                            </li>
                            <li>
                              <%= button_to 'Destroy', category_path(category.id), data: {:confirm => 'Are you sure?'}, :method => :delete, class:'dropdown-item' %>
                            </li>
                            
                        </ul>
            </div>
        </div>













    </div>








       
        <% end %>
  </div>
</div>




<%= link_to new_category_path  do %>
<button type="button" class="btn btn-success btn-lg btn-block btn_new_cat" style=" width:100%; border-radius:0; height:5%">New Category</button>

        
<% end %>

app/views/categories/new.html.erb
<section class="section-wrapper">
    <div class="section-heading">
        <span class="fs-4">
            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
            New category
        </span>
    </div>
    <div class="section-content container">
            <%= form_with model: @category, url: categories_path, class: 'row', :html => { :multipart => true } do |f| %>
                <i class="fa fa-credit-card fa-5x home_icons d-flex justify-content-center" aria-hidden="true"></i> 
                    <div class="form-group pb-2">
                        <%= f.label :name, "Category Name", class: "text-muted" %>
                        <%= f.text_field :name, :class => "form-control", placeholder: 'Type here ..' %>
                    </div>
                    <div class="form-group">
                        <%= f.submit "Create", :class => "btn btn-success btn-md btn-block d-flex justify-content-center" %>
                    </div>
            <% end %>
    </div>
</section>

app/views/categories/show.html.erb
<section class="watch-board">
    <div class="cat_name">
        <span style="margin-left:0.1rem; padding-top: 1rem; font-size: 1.5rem;"><%= @category.name %></span> 
    </div>
    <div>
        <span class="m-1" style="float:right; font-weight: bold;">
        <%= number_to_currency(@category.total_amount) %></span>
    </div>
</section>
<section class="list-wrapper expense-height">
<div class="text-muted topic-expense side">EXPENSES</div>
    <ul>
        <% @expenses.each do |expense| %>

        <div class="alert alert-secondary" role="alert">
            <div class="row d-flex justify-content-center mt-2">
            <div class="col-1">
               <i class="fa fa-tag fa-2x home_icons" aria-hidden="true"></i> 
            </div>
            <div class="col-9  justify-content-center">
                <div class="expense">
                    <%= expense.name %><br />
                    <span class="text-muted date-expense"><%= expense.date_of_expense.strftime("%B %d, %Y") %> </span>
                    <span style="float:right; font-weight: bold;">
                        <%= number_to_currency(expense.amount) %>
                    </span>
                </div>
            </div>
            <div class="col-2">
                <%= button_to ' <i class="fa fa-trash fa-2x trash shadow" aria-hidden="true"></i>'.html_safe, expense_path(expense.id),:method => :delete , class: 'btn_delete'%>
            </div>
        </div>
    </div>










             
        <% end %>
   </ul>
</section>
<%= link_to new_expense_path, class: 'foot-button' do %>
<button type="button" class="btn btn-success btn-lg btn-block btn_new_cat" style=" width:100%; border-radius:0; height:5%"> Add Expense</button>

<% end %>

app/views/expenses/index.html.erb
<h1>Expenses Page</h1>

app/views/expenses/new.html.erb
<section class="section-wrapper">
    <div class="section-heading">
        <span class="fs-4">
            <i class="fa fa-credit-card" aria-hidden="true"></i>
            New expense
        </span>
    </div>
    <div class="section-content container mt-4">
        <%= form_with model: @expense, url: expenses_path  do |f| %>
        <div class="form-group pb-2">
            <%= f.date_field :date_of_expense, :class => "form-control" %>
        </div>
        <div class="form-group pb-2">
            <%= f.label :name, "What did you spend on?", class: "text-muted" %>
            <%= f.text_field :name, :class => "form-control", maxlength: '200' %>
        </div>
        <div class="form-group pb-2">
            <%= f.label :amount, "How much did you spend ($)", class: "text-muted" %>
           <%= f.number_field :amount, class: 'form-control' %>
        </div>
        <div class="form-group pb-2">
            <%= f.label :categories, "Expense category", class: "text-muted" %>
            <%= f.select :categories, @categories.map { |category| [category.name, category.id] }, {:required => true, include_hidden: false, include_blank: ' - '}, {:class => 'form-control', :multiple => false} %>
        </div>
        <div class="form-group">
            <%= f.submit "Add", :class => "btn submit-btn form-control" %>
        </div>
        <% end %>
    </div>
</section>

app/views/home/welcome.html.erb
<section class="container home_body">
   <div class="row logo">
        <%= image_tag("saveit.png") %>
   </div>
   <div class="account  ">
      <%= link_to 'LOG IN', new_user_session_path, class: 'btn btn-primary btn-lg btn-block acc_bttn' %>
      <%= link_to 'SIGN UP', new_user_registration_path,  class: 'btn btn-secondary  btn-lg btn-block acc_bttn'%>
   </div>
   </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <!-- Option 1: Include in HTML -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
  </head>

  <body class=layout_body>
     <% if current_user %>
      <nav class="navbar navbar-light bg-light justify-content-between nav_bar">
          <%= link_to authenticated_root_path do %><i class="fa fa-bars back_btn"></i> <% end %>
           <%= link_to authenticated_root_path do %> <span class="navbar-brand d-flex justify-content-center white_text">SAVEIT</span>   <% end %>
         <%= button_to 'SignOut'.html_safe, destroy_user_session_path, method: :delete,  class: "btn btn-sm  btn-danger white_text action_btn" %>
      </nav>
     <%end%>
    
    <%= yield %>
   
  </body>
</html>